In [2]:
#numpy

import numpy as np

a = np.array([2,3,4])

print(a)
print(type(a))

[2 3 4]
<class 'numpy.ndarray'>


In [3]:
#Performing Basic Operation
#Addition

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_addition = array1 + array2

print(result_addition)

[ 2  4  6  8 10]


In [4]:
#Substraction

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_subtraction = array2 - array1

print(result_subtraction)

[0 0 0 0 0]


In [7]:
#Division

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,6,9,12,20])

result_addition = array2 / array1

print(result_addition)

[1. 3. 3. 3. 4.]


In [8]:
#Multiplication

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_multiplication = array1 * array2

print(result_multiplication)

[ 1  4  9 16 25]


In [9]:
#Square Root

array1 = np.array([1,2,3,4,5])

result_sqrt = np.sqrt(array1)

print(result_sqrt)

[1.         1.41421356 1.73205081 2.         2.23606798]


In [14]:
#Summation

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_sum = np.sum(array1)

print(result_sum)

15


In [17]:
#Mean

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_mean = np.mean(array1)

print(result_mean)

3.0


In [18]:
#Maximum and Minimum

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_max = np.max(array1)
result_min = np.min(array2)

print(result_max)
print(result_min)

5
1


In [24]:
#Multi dimensional array

#2D array
array1 = np.array([ [1, 2, 3], [4, 5, 6] ])

# print(array1)
# print(array1.size)
# print(array1.shape)


#3D Array
array2 = np.array( [  [ [1,2,3], [1,2,3] ], [ [3,4,5], [6,7,8] ]  ] )

print(array2,"\n")

#Shape attribute of a NumPy array describes it's dimmensions. It returns a tuple representing the length in each array.
print(array2.shape)



[[[1 2 3]
  [1 2 3]]

 [[3 4 5]
  [6 7 8]]] 

(2, 2, 3)


In [26]:
#dtype
#find inside array data types

array = np.array([1.1, 2, 3])
print(array.dtype) #Output: int64

float64


In [27]:
#ndim
#The ndim attribute indicates the number of dimensions (axes ) in the array.

array = np.array([ [ [1, 2], [3, 4], [5, 6] ]])
print(array.ndim) #output 3

3


In [30]:
#numpy array indexing

array_1 = np.array([1, 2, 3, 4])
print(array_1[2]) #output is 3

array_2 = np.array([[1, 2, 3], [4, 5, 6]])
print('2nd element on lst row: ', array_1[0])
print('2nd element on lst row: ', array_2[0,1])

3
2nd element on lst row:  1
2nd element on lst row:  2


In [39]:
# create a 2D numpy array which has dimension 4*5 which contends the numbers 1 to 20.
# perform the following on this array add 10 to every element.
# multiply every element by 2. calculate the square of each element

array_22 = np.array([ [1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]])
result_addition = array_22 + 10
print(result_addition,"\n")

result_multiply = array_22 * 2
print(result_multiply,"\n")

result_square = array_22 ** 2
print(result_square,"\n")

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]] 

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]] 

[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]] 



In [42]:
#Boolean Indexing in Numpy

import numpy as np

arr = np.array([10,20,30,40,50])

condition = arr > 25

print(condition)

#Filtering based on condition
filtered = arr[arr > 25]

print(filtered)

[False False  True  True  True]
[30 40 50]


In [43]:
#Combining Multiple Conditions

arr = np.array([10, 20, 30, 40, 50])

filtered_combined = arr[(arr>20) & (arr<50)]
print(filtered_combined)

[30 40]


In [47]:
#Array Initialization

array_1 = np.zeros(5, dtype=float) #dtype for changeing data type to float #[0, 0, 0, 0, 0] 1D
print(array_1)

array_2 = np.zeros((2,3)) #shape is given here #[ [0, 0, 0, 0, 0], [0, 0, 0, 0, 0] ] 2D
print(array_2)



[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [49]:
#Using full
#This fills the array completly using given value
array_1 = np.full(4,7) #[7,7,7,7]
print(array_1,"\n")

array_2 = np.full((2,3),8) #[7,7,7,7]
print(array_2)

[7 7 7 7] 

[[8 8 8]
 [8 8 8]]


In [50]:
#used to create empty arrays.
#values are set from garbage collector
#performance and flexibility when using
array_1 = np.empty((2,3))
print(array_1)

[[4.e-323 4.e-323 4.e-323]
 [4.e-323 4.e-323 4.e-323]]


In [54]:
# create a 1D numpy array with values form 1 to 20. # use boolean indexing to extract all even numbers

array_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
results = array_1[array_1 % 2 == 0]
print(results)


[ 2  4  6  8 10 12 14 16 18 20]


In [56]:
# create a numpy 1D array with elements 10,20,30,40,50. 
# use boolean indexing to extract all elements greater than the mean of the array

arr = np.array([10,20,30,40,50])
mean_ = np.mean(arr) 
result = arr[arr > mean_]
print(result)

[40 50]


In [5]:
#Pandas

import pandas as pd

In [4]:
#DataFrame

import pandas as pd

#Creating DataFrame from a dictionary

data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age':[25, 30, 35, 40]}

df = pd.DataFrame(data)

print(df)

print(df.loc[1, "Name"]) #loc to select
print(df.iloc[1, 0]) #iloc for access elements by row index and column index
print(df.loc[1]) # to access a certain row

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
Bob
Bob


In [5]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age':[25, 30, 35, 40]}

print(df.loc[[0,1]]) #Multiple rows

    Name  Age
0  Alice   25
1    Bob   30


In [6]:
#Named indexes
import pandas as pd

data = {"Calories": [420, 380, 390], "Age":[25, 30, 35]}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
print(df,"\n")
print(df.loc["day2"],"\n")
print(df.loc[["day1","day2"]],"\n")

      Calories  Age
day1       420   25
day2       380   30
day3       390   35 

Calories    380
Age          30
Name: day2, dtype: int64 

      Calories  Age
day1       420   25
day2       380   30 

