In [2]:
#numpy

import numpy as np

a = np.array([2,3,4])

print(a)
print(type(a))

[2 3 4]
<class 'numpy.ndarray'>


In [3]:
#Performing Basic Operation
#Addition

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_addition = array1 + array2

print(result_addition)

[ 2  4  6  8 10]


In [4]:
#Substraction

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_subtraction = array2 - array1

print(result_subtraction)

[0 0 0 0 0]


In [7]:
#Division

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,6,9,12,20])

result_addition = array2 / array1

print(result_addition)

[1. 3. 3. 3. 4.]


In [8]:
#Multiplication

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_multiplication = array1 * array2

print(result_multiplication)

[ 1  4  9 16 25]


In [9]:
#Square Root

array1 = np.array([1,2,3,4,5])

result_sqrt = np.sqrt(array1)

print(result_sqrt)

[1.         1.41421356 1.73205081 2.         2.23606798]


In [14]:
#Summation

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_sum = np.sum(array1)

print(result_sum)

15


In [17]:
#Mean

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_mean = np.mean(array1)

print(result_mean)

3.0


In [18]:
#Maximum and Minimum

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_max = np.max(array1)
result_min = np.min(array2)

print(result_max)
print(result_min)

5
1


In [20]:
#Multi dimensional array

array1 = np.array([ [1, 2, 3], [4, 5, 6] ])

print(array1)

print(array1.size)
print(array1.shape)



[[1 2 3]
 [4 5 6]]
6
(2, 3)
