In [2]:
#numpy

import numpy as np

a = np.array([2,3,4])

print(a)
print(type(a))

[2 3 4]
<class 'numpy.ndarray'>


In [3]:
#Performing Basic Operation
#Addition

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_addition = array1 + array2

print(result_addition)

[ 2  4  6  8 10]


In [4]:
#Substraction

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_subtraction = array2 - array1

print(result_subtraction)

[0 0 0 0 0]


In [7]:
#Division

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,6,9,12,20])

result_addition = array2 / array1

print(result_addition)

[1. 3. 3. 3. 4.]


In [8]:
#Multiplication

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_multiplication = array1 * array2

print(result_multiplication)

[ 1  4  9 16 25]


In [9]:
#Square Root

array1 = np.array([1,2,3,4,5])

result_sqrt = np.sqrt(array1)

print(result_sqrt)

[1.         1.41421356 1.73205081 2.         2.23606798]


In [14]:
#Summation

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_sum = np.sum(array1)

print(result_sum)

15


In [17]:
#Mean

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_mean = np.mean(array1)

print(result_mean)

3.0


In [18]:
#Maximum and Minimum

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

result_max = np.max(array1)
result_min = np.min(array2)

print(result_max)
print(result_min)

5
1


In [24]:
#Multi dimensional array

#2D array
array1 = np.array([ [1, 2, 3], [4, 5, 6] ])

# print(array1)
# print(array1.size)
# print(array1.shape)


#3D Array
array2 = np.array( [  [ [1,2,3], [1,2,3] ], [ [3,4,5], [6,7,8] ]  ] )

print(array2,"\n")

#Shape attribute of a NumPy array describes it's dimmensions. It returns a tuple representing the length in each array.
print(array2.shape)



[[[1 2 3]
  [1 2 3]]

 [[3 4 5]
  [6 7 8]]] 

(2, 2, 3)


In [26]:
#dtype
#find inside array data types

array = np.array([1.1, 2, 3])
print(array.dtype) #Output: int64

float64


In [27]:
#ndim
#The ndim attribute indicates the number of dimensions (axes ) in the array.

array = np.array([ [ [1, 2], [3, 4], [5, 6] ]])
print(array.ndim) #output 3

3


In [30]:
#numpy array indexing

array_1 = np.array([1, 2, 3, 4])
print(array_1[2]) #output is 3

array_2 = np.array([[1, 2, 3], [4, 5, 6]])
print('2nd element on lst row: ', array_1[0])
print('2nd element on lst row: ', array_2[0,1])

3
2nd element on lst row:  1
2nd element on lst row:  2


In [39]:
# create a 2D numpy array which has dimension 4*5 which contends the numbers 1 to 20.
# perform the following on this array add 10 to every element.
# multiply every element by 2. calculate the square of each element

array_22 = np.array([ [1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]])
result_addition = array_22 + 10
print(result_addition,"\n")

result_multiply = array_22 * 2
print(result_multiply,"\n")

result_square = array_22 ** 2
print(result_square,"\n")

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]] 

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]] 

[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]] 



In [42]:
#Boolean Indexing in Numpy

import numpy as np

arr = np.array([10,20,30,40,50])

condition = arr > 25

print(condition)

#Filtering based on condition
filtered = arr[arr > 25]

print(filtered)

[False False  True  True  True]
[30 40 50]


In [43]:
#Combining Multiple Conditions

arr = np.array([10, 20, 30, 40, 50])

filtered_combined = arr[(arr>20) & (arr<50)]
print(filtered_combined)

[30 40]


In [47]:
#Array Initialization

array_1 = np.zeros(5, dtype=float) #dtype for changeing data type to float #[0, 0, 0, 0, 0] 1D
print(array_1)

array_2 = np.zeros((2,3)) #shape is given here #[ [0, 0, 0, 0, 0], [0, 0, 0, 0, 0] ] 2D
print(array_2)



[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [49]:
#Using full
#This fills the array completly using given value
array_1 = np.full(4,7) #[7,7,7,7]
print(array_1,"\n")

array_2 = np.full((2,3),8) #[7,7,7,7]
print(array_2)

[7 7 7 7] 

[[8 8 8]
 [8 8 8]]


In [50]:
#used to create empty arrays.
#values are set from garbage collector
#performance and flexibility when using
array_1 = np.empty((2,3))
print(array_1)

[[4.e-323 4.e-323 4.e-323]
 [4.e-323 4.e-323 4.e-323]]


In [54]:
# create a 1D numpy array with values form 1 to 20. # use boolean indexing to extract all even numbers

array_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
results = array_1[array_1 % 2 == 0]
print(results)


[ 2  4  6  8 10 12 14 16 18 20]


In [56]:
# create a numpy 1D array with elements 10,20,30,40,50. 
# use boolean indexing to extract all elements greater than the mean of the array

arr = np.array([10,20,30,40,50])
mean_ = np.mean(arr) 
result = arr[arr > mean_]
print(result)

[40 50]


In [5]:
#Pandas

import pandas as pd

In [4]:
#DataFrame

import pandas as pd

#Creating DataFrame from a dictionary

data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age':[25, 30, 35, 40]}

df = pd.DataFrame(data)

print(df)

print(df.loc[1, "Name"]) #loc to select
print(df.iloc[1, 0]) #iloc for access elements by row index and column index
print(df.loc[1]) # to access a certain row

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
Bob
Bob


In [5]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age':[25, 30, 35, 40]}

print(df.loc[[0,1]]) #Multiple rows

    Name  Age
0  Alice   25
1    Bob   30


In [9]:
#Named indexes
import pandas as pd

data = {"Calories": [420, 380, 390], "Age":[25, 30, 35]}

df2 = pd.DataFrame(data, index = ["day1", "day2", "day3"])
print(df2,"\n")
print(df2.loc["day2"],"\n")
print(df2.loc[["day1","day2"]],"\n")
print(df2['Calories'])

      Calories  Age
day1       420   25
day2       380   30
day3       390   35 

Calories    380
Age          30
Name: day2, dtype: int64 

      Calories  Age
day1       420   25
day2       380   30 

day1    420
day2    380
day3    390
Name: Calories, dtype: int64


In [10]:
# Dimensions (Shape)
# Returns number of rows and columns

data = {"Calories": [420, 380, 390], "Age":[25, 30, 35]}

df2 = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df2.shape)

(3, 2)


In [12]:
#DataFrame Columns

df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
print(df.columns)
print(list[df2.columns])

Index(['A', 'B'], dtype='object')
list[Index(['Calories', 'Age'], dtype='object')]


In [13]:
#DataFrame size

df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
print(df.size)

4


In [16]:
#Data type

df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})

print(df.values,'\n')
print(type(df.values))

[[1 3]
 [2 4]] 

<class 'numpy.ndarray'>


In [8]:
import pandas as pd
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4], 'C': [6, 6]})

print(df.values,'\n')
print(df,'\n')
print(len(df)) #amount of rows

[[1 3 6]
 [2 4 6]] 

   A  B  C
0  1  3  6
1  2  4  6 

2


In [21]:
# You are a data analysyst to a company. the company has provided you with the above table containing sales data.
# Your task is to analyse the sales data using python and pandas to answer some key business question.

    # calculate the total revenue for each order. (add a new coloumn total revenue to store the total revenue for each order)
    # Identify the best selling product (find the product with the highest total sales revenue)
    
data = {"Order_Id":[101,102,103,104,105],
        "Product":["Laptop","SmartPhone","Desk Chair","Monitor","BookShelf"],
        "Category":["Electronics","Electronics","Furniture","Electronics","Furniture"],
        "Quantity":[2,5,10,4,2],
        "Price_per_Unit":[1000,800,150,200,300],
        "Region":["North","South","East","West","North"]
        }

df = pd.DataFrame(data)
df['Total Revenue'] = df['Quantity'] * df['Price_per_Unit']
print(df)

product_revenue = df.groupby('Product')['Total Revenue'].sum() # Calculated the total revenue for each product
best_selling_product = product_revenue.idxmax() #This finds the column name of the maximum value
highest_revenue = product_revenue.max() #this finds the highest revenue


print('\n')    
print(f"The best selling product is {best_selling_product} with total revenue of {highest_revenue}.")

   Order_Id     Product     Category  Quantity  Price_per_Unit Region  \
0       101      Laptop  Electronics         2            1000  North   
1       102  SmartPhone  Electronics         5             800  South   
2       103  Desk Chair    Furniture        10             150   East   
3       104     Monitor  Electronics         4             200   West   
4       105   BookShelf    Furniture         2             300  North   

   Total Revenue  
0           2000  
1           4000  
2           1500  
3            800  
4            600  


The best selling product is SmartPhone with total revenue of 4000.


In [15]:
#Mean
data = {"Calories": [420, 380, 390], "Age":[25, 30, 35]}

df = pd.DataFrame(data)
print(df.mean())

Calories    396.666667
Age          30.000000
dtype: float64


In [16]:
#Sum

data = {"Calories": [420, 380, 390], "Age":[25, 30, 35]}

df = pd.DataFrame(data)
print(df.sum())

Calories    1190
Age           90
dtype: int64


In [17]:
#Describe
data = {"Calories": [420, 380, 390], "Age":[25, 30, 35]}

df = pd.DataFrame(data)
print(df.describe())

         Calories   Age
count    3.000000   3.0
mean   396.666667  30.0
std     20.816660   5.0
min    380.000000  25.0
25%    385.000000  27.5
50%    390.000000  30.0
75%    405.000000  32.5
max    420.000000  35.0


In [19]:
#Filtering

data = {"Name":["Alice","Age","Score"], "Age":[24,27,22,32], "David":[85,70,90,88]}

filtered_df = df[df['Age'] > 25]
print(filtered_df,'\n',type(filtered_df))

   Calories  Age
1       380   30
2       390   35 
 <class 'pandas.core.frame.DataFrame'>
